name: Test and Deploy App to Oracle VPS

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.1.1

      - name: Run Deno Lint
        run: deno lint
  
  format:
    name: Format Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.1.1

      - name: Run Deno Format
        run: deno fmt

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.1.1

      - name: Run Deno Tests
        run: deno test --allow-net --allow-env --allow-read
        
  deploy:
    name: Deploy to Oracle VPS
    runs-on: ubuntu:latest
    
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script:
            cd elte-fullstack
            git pull origin master
            sudo docker compose down
            sudo docker compose up --build -d
    
